version: '3.7'

services:
  orion-api:
    container_name: orion-api
    image: orion-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4444:4444
    command: npm run start:dev
    environment:
      JWT_SECRET_KEY: 3RWS8GmVfz6Ax7l0q5nQ2RUySvPsdh0aK3GSY4mTRhlICvi8Il
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: orion
      DB_CONNECTION_STRING: mysql://orion_root:j5m966qp7jiypfda@orion-mysql:3306
      MARVEL_API_KEY: 62b6e0cdc597884f34922038b64eb82e
      MARVEL_PRIVATE_KEY: f6ef79b8c8126fe30a11921202f27cf11696b24c
      GOOGLE_TRANSLATE_API_KEY: AIzaSyD4vZC8mYs84cLpbMub2oW9_RoD9P13-Hg
      GOOGLE_TRANSLATE_PROJECT_ID: folkloric-grid-403811
    networks:
      - orion-connect

  orion-mysql:
    container_name: orion-mysql
    image: mysql
    environment:
      MYSQL_USER: orion_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: orion
    ports:
      - 3306:3306
    volumes:
      - ~/docker/volumes/OrionApi_MySQL:/var/lib/mysql
    networks:
      - orion-connect
    logging:
      driver: none

networks:
  orion-connect:
    driver: bridge
