version: '3.7'

services:
  orion-api:
    container_name: orion-api
    image: orion-api:dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4444:4444
    command: npm run start:dev
    environment:
      NODE_ENV: development
      SERVER_PORT: 4444
      DB_DATABASE: orion
      DB_CONNECTION_STRING: mongodb://orion_root:j5m966qp7jiypfda@orion-mongo:27017
    networks:
      - orion-connect
  
  orion-mongo:
    container_name: orion-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: orion_root
      MONGO_INITDB_ROOT_PASSWORD: j5m966qp7jiypfda
      MONGO_INITDB_DATABASE: orion
    ports:
      - 27017:27017
    volumes:
      - ~/docker/volumes/OrionApi_MongoDB:/data/db
    networks:
      - orion-connect
    logging:
      driver: none
  
  orion-mysql:
    container_name: orion-mysql
    image: mysql
    environment:
      MYSQL_USER: orion_root
      MYSQL_PASSWORD: j5m966qp7jiypfda
      MYSQL_ROOT_PASSWORD: m45ug42qkr5pdzbb
      MYSQL_DATABASE: orion
    ports:
      - 3306:3306
    volumes:
      - ~/docker/volumes/OrionApi_MySQL:/var/lib/mysql
    networks:
      - orion-connect
    logging:
      driver: none

networks:
  orion-connect:
    driver: bridge
